<a href="https://colab.research.google.com/github/victorlee0923-creator/ML_Book_Practice/blob/main/%E6%A9%9F%E5%99%A8%E5%AD%B8%E7%BF%92%E8%AD%89%E7%85%A70_4_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
!pip install jupyterlab

In [ ]:
!pip show jupyterlab

#0-4-1 向量與矩陣

In [10]:
#用list來實作向量運算(是最遜的作法)
A=[1,2,3]
B=[4,5,6]

def vector_add(v,w):
  return [v_i+w_i for v_i,w_i in zip(v,w)]
def vector_dot_product(v,w):
  return sum(v_i*w_i for v_i,w_i in zip(v,w))
print(vector_add(A,B))
print(vector_dot_product(A,B))

[5, 7, 9]
32


In [11]:
#利用numpy陣列array來實作向量才是最棒的
import numpy as np

A=np.array([1,2,3])
B=np.array([4,5,6])
print('向量相加',A+B)
print('純量向量相乘:',3*A)
print('向量相乘:',A*B)
print('向量內積:',np.dot(A,B))
print('向量長度:',np.linalg.norm(A))

向量相加 [5 7 9]
純量向量相乘: [3 6 9]
向量相乘: [ 4 10 18]
向量內積: 32
向量長度: 3.7416573867739413


In [12]:
#三個主要屬性
arr=np.array([1,2,3,4,5,6])
print(arr.ndim) #屬性 : 維度
print(arr.shape) #屬性 : 形狀
print(arr.dtype) #屬性 : 資料型態

1
(6,)
int64


In [13]:
#改變陣列的形狀以及維度
arr.shape=(2,3) #tuple
# arr.shape=2,3 #這裡的2,3基本上是未打包的tuple的寫法
print(arr)

arr1=arr.reshape((3,2))
print(arr1)

[[1 2 3]
 [4 5 6]]
[[1 2]
 [3 4]
 [5 6]]


以下為numpy的矩陣資料結構，但通常不建議使用，因為多數運算的函式回傳的是ndarray資料型態而不是matrix

In [ ]:
#在最新的numpy中，np.mat已經被棄用了，所以執行這個cell也不會成功
# import numpy as np
# matrix=np.mat([[1,2,3],[4,5,6]])
# print(matrix)

In [ ]:
#矩陣運算
A=np.array([[1,2,3],[4,5,6]])
B=np.array([[1,0,0],[0,1,1],[1,0,1]])
print("--------矩陣相乘---------")
print(np.dot(A,B))
print("--------轉置矩陣---------")
print(np.transpose(A))
print(A.T)
print(A.transpose())
print("-------反矩陣----------")
print(np.linalg.inv(B))
print("-------正反矩陣相乘----------")
C=np.linalg.inv(B)
print(np.dot(B,C))

In [15]:
#避免不可逆矩陣無法進行反矩陣而出現錯誤的情況
try:
  inv = np.linalg.inv(B)
except np.linalg.LinAlgError:
  print('不可逆矩陣')

In [ ]:
#轉置對一維陣列沒有用，要寫成二維陣列才能使用轉置
arr=np.array([1,2,3])#一維陣列
print(arr.T)
arr=np.array([[1,2,3]]) #二維陣列
print(arr.T)

In [ ]:
#將矩陣攤平 flatten()
A=np.array([[1,2,3],[4,5,6]])
A.flatten() #得到一維陣列

In [ ]:
#得到一個二維陣列1X6(也可以6X1)，那個-1的解釋在heptabase中有
A.reshape(1,-1)
# A.reshape(-1,1) #轉換成6X1的二維陣列